### ISSUE TITLE
Adding Qt dependencies

### ISSUE THREAD

**Issue by jakirkham** [jjhelmus/conda-forge-docker-image#2]
Not sure if I have the right repo. Was added here ( https://github.com/conda-forge/docker-images/issues/1 ) initially. Sorry still figuring this stuff out. :) 

So, I have a recipe that uses Qt, but it is missing some dependencies like `libXext.so.6`. Would be nice to add these to the image.

@jjhelmus, I think I saw one of your feedstocks (don't remember which one) adds this stuff explicitly. Is that the way we should do this or can we add them to the docker image?

**Comment by jjhelmus** [comment]
Answered in the linked repo.  I that is a better place for this conversation.

**Comment by jakirkham** [comment]
Yeah, I will close this.
